### ISSUE TITLE
[bug] `pragma: allowlist nextline secret` isn't always respected

### ISSUE THREAD

**Issue by ExplodingCabbage** [Yelp/detect-secrets#435]
After a few experiments, I haven't been able to figure out the logic governing when it does and doesn't work.

Here's an example where the pragma does work:

```
# pragma: allowlist nextline secret
{"foo": "a16e770f5fe56019"}
```

Here's an example where it doesn't:

```
# pragma: allowlist nextline secret
foo: a16e770f5fe56019
```

detect-secrets will return no results for the first file but report a high entropy hex string in the second, disregarding the pragma.

The normal `allowlist secret` pragma seems to work in the second case, but not the `nextline` version.

**Comment by holyjak** [comment]
I have a similar problem where none of the two variants work. With the nextline:

```clojure
;; pragma: allowlist nextline secret
{:user {:signing {:gpg-key "5AA361214163F2CD"} ;; my keybase key
```

**Comment by jjneely** [comment]
This bug makes this project almost unusable.  There are many text file formats where one cannot add an inline pragma -- the pragma must be on a separate line.

**Comment by jpdakran** [comment]
@ExplodingCabbage @holyjak @jjneely @choman Can you please outline which file types you are seeing this issue in with an example snippet of the failing case. I am actively working on this issue and would like more test cases for verification. Thank you.

**Comment by petercj1** [comment]
I've just been experiencing this issue this morning. The file extension is .cfg (specifically, it is airflow.cfg). The offending line:

```# pragma: allowlist nextline secret
result_backend = db+mysql://airflow:airflow@localhost:3306/airflow```

The response on committing, with detect-secrets in the precommit hooks:

```Secret Type: Basic Auth Credentials
Location:    docker/config/airflow.cfg:618```

**Comment by jpdakran** [comment]
@petercj1 What version of detect-secrets are you using?

**Comment by petercj1** [comment]
Ah, good question. It is 1.2.0

**Comment by jpdakran** [comment]
Thats, interesting. I am running the same version and it seems to be filtering out fine. Can you tell me the output of:
`detect-secrets -v scan docker/config/airflow.cfg` and 
`detect-secrets-hook -v scan docker/config/airflow.cfg`
Also in your `.pre-commit-config.yaml` can you post a snippet of your detect-secrets configuration?

**Comment by jpdakran** [comment]
Ok couple things I'm noticing. 
A) There are no [INFO] debug lines in your first snipped did you forget to paste those? In addition I am seeing the following debug lines in both command outputs:
```
[scan]	INFO	Checking file: airflow.cfg
[scan]	INFO	Skipping secret due to `detect_secrets.filters.allowlist.is_line_allowlisted`.
```
B) The first command output verifies that the secret is filtered out? Which is what we want?
C) The second command output verifies that the secret is filtered out?
D) In your pre-commit config are you using v1.2.0? I don't see a specified version. Mine looks like the following: 
```
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    -   id: detect-secrets
        args: [--baseline, .secrets.baseline]
        additional_dependencies: ['gibberish-detector']
```

**Comment by sergei-ivanov** [comment]
Looks like it is still a problem with `detect-secrets` v1.5.0 when checking `.pre-commit-config.yaml` files that were updated with `pre-commit autoupdate --freeze`.
For example:
```yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # pragma: allowlist nextline secret
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
```
...results in:
```
    ".pre-commit-config.yaml": [
      {
        "type": "Hex High Entropy String",
        "filename": ".pre-commit-config.yaml",
        "hashed_secret": "26f89e75489173ffe046cc843b9a983e65020901",
        "is_verified": false,
        "line_number": 7
      },
...
```
The only way I managed to suppress it without excluding the whole file is by running:
```bash
detect-secrets -v scan --exclude-lines '^\s*rev:\s*(.+)\s*#\s*frozen:\s*(.+)$' .pre-commit-config.yaml
```

**Comment by Pwuts** [comment]
I'm also still seeing this with v1.5.0:

```yaml
# docker-compose.platform.yaml

# Common backend environment - Docker service names
x-backend-env: &backend-env # Docker internal service hostnames (override localhost defaults)
  PYRO_HOST: "0.0.0.0"
  AGENTSERVER_HOST: rest_server
  SCHEDULER_HOST: scheduler_server
  DATABASEMANAGER_HOST: database_manager
  EXECUTIONMANAGER_HOST: executor
  NOTIFICATIONMANAGER_HOST: notification_server
  CLAMAV_SERVICE_HOST: clamav
  DB_HOST: db
  REDIS_HOST: redis
  RABBITMQ_HOST: rabbitmq
  # Override Supabase URL for Docker network
  SUPABASE_URL: http://kong:8000
  # Database connection string for Docker network
  # This cannot be constructed like in .env because we cannot interpolate values set here (DB_HOST)
  # pragma: allowlist nextline secret
  DATABASE_URL: postgresql://postgres:your-super-secret-and-long-postgres-password@db:5432/postgres?connect_timeout=60&schema=platform
  # pragma: allowlist nextline secret
  DIRECT_URL: postgresql://postgres:your-super-secret-and-long-postgres-password@db:5432/postgres?connect_timeout=60&schema=platform

# ...
```
