### ISSUE TITLE
detect-secrets-hook not recognizing --word-list argument with pre-commit framework

### ISSUE THREAD

**Issue by wbreza** [Yelp/detect-secrets#497]
**Version: 1.1.0** (also tested with 1.0.3)

```ini
# requirements.txt

pre-commit==2.15.0
detect-secrets==1.1.0
pyahocorasick==1.4.2
```

I'm attempting to integrate additional arguments into my `.pre-commit-config.yaml` file.

A slim implementation is working with no issues

## Working

```yaml
# .pre-commit-config.yaml

repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
```

## Not Working
```yaml
# .pre-commit-config.yaml

repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args:
          [
            "--baseline",
            ".secrets.baseline",
            "--word-list",
            "secrets-wordlist.txt",
          ]
```

### Steps to reproduce

```bash
# Create & activate python virtual env

pip install -r requirements.txt
pre-commit install

# Stage some files to commit
git commit -am "Testing secret detection" 
```

When I attempt to add additional argument such as the `--word-list` argument it fails with the following:

```
Detect secrets...........................................................Failed
- hook id: detect-secrets
- exit code: 2

usage: detect-secrets-hook
       [-h]
       [-v]
       [--version]
       [-C <path>]
       [-c NUM_CORES]
       [--baseline FILENAME]
       [--list-all-plugins]
       [-p PLUGIN]
       [--base64-limit [BASE64_LIMIT]]
       [--hex-limit [HEX_LIMIT]]
       [--disable-plugin DISABLE_PLUGIN]
       [-n | --only-verified]
       [--exclude-lines EXCLUDE_LINES]
       [--exclude-files EXCLUDE_FILES]
       [--exclude-secrets EXCLUDE_SECRETS]
       [-f FILTER]
       [--disable-filter DISABLE_FILTER]
       [filenames [filenames ...]]

detect-secrets-hook: error: unrecognized arguments: --word-list
```

Oddly enough, if I execute the hook directly with the following command/args everything works as expected.

```bash
# Works as expected
detect-secrets-hook --baseline .secrets.baseline --word-list secrets-wordlist.txt .env
```

Any ideas?
