### ISSUE TITLE
Jupyter Notebook Support

### ISSUE THREAD

**Issue by ghost** [Yelp/detect-secrets#549]
I tried running detect-secrets against Jupyter Notebooks (.ipynb), but those files contain hashes of my interpreter.
Those hashes get flagged as high entropy string. Currently I exclude Notebooks for this very reason, but I would love to get those Notebooks still checked.
I use VS Code as IDE.
Opening the ipynb with a plain text editor shows the flagged line on the bottom of the file.
```
{
  [...]
  "metadata": {
    "interpreter": {
      "hash": "HIGH-ENTROPY-STRING-HASH"
    }, 
   [...]
  }
  [...]
}
```

**Comment by klaerik** [comment]
Ran into this issue and was able to work around it with some line exclusions. Beyond the hash fields there's also the need to exclude the base64-encoded images and ids.

Here is an example from the `.pre-commit-config.yaml`:

```yaml
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        name: 'detect-secrets'
        args: ['--exclude-files', '.*\.ipynb$', ]
      - id: detect-secrets
        name: 'detect-secrets-jupyter'
        args: ['--exclude-files', '.*[^i][^p][^y][^n][^b]$', '--exclude-lines', '"(hash|id|image/\w+)":.*', ]
```
