### ISSUE TITLE
datect secret audit doesnt work

### ISSUE THREAD

**Issue by garry-t** [Yelp/detect-secrets#622]
After I generated baseline file i got around 100 entries in file. I know that some of them are secrets.
When I run audit it produce error, cant figure out what is the problem. 
I used latest version 1.3.0
```
".circleci/config.yml": [
      {
        "type": "Hex High Entropy String",
        "filename": ".circleci/config.yml",
        "hashed_secret": "963d6519f46177770aad8c3ffa8713824daff92c",
        "is_verified": false,
        "line_number": 141
      },
```

```
Secret:      1 of 62
Filename:    .circleci/config.yml
Secret Type: Hex High Entropy String
----------
ERROR: Secret not found on line 5!
Try recreating your baseline to fix this issue.

```

**Comment by lorenzodb1** [comment]
> Try recreating your baseline to fix this issue.

 Did this fix the issue?

**Comment by garry-t** [comment]
> > Try recreating your baseline to fix this issue.
> 
> Did this fix the issue?
no)

**Comment by jpdakran** [comment]
@garry-t Can you post a snippet of the `.circleci/config.yml` file that is failing?

**Comment by garry-t** [comment]
> @garry-t Can you post a snippet of the `.circleci/config.yml` file that is failing?

sorry I cant, there are a lot of confidential info. 
But string 141 it is slack webhook url `https://hooks.slack.com/services/[A-Z][0-9]/[A-Z][0-9]/[0-9]`

**Comment by lorenzodb1** [comment]
@garry-t could you then provide us with a mock `.circleci/config.yml` (i.e. without any of your info) that we could still use to reproduce the issue?

**Comment by garry-t** [comment]
> @garry-t could you then provide us with a mock `.circleci/config.yml` (i.e. without any of your info) that we could still use to reproduce the issue?

let me try

**Comment by garry-t** [comment]
Mocking file on 1000 strings hard job. Not sure how to properly mock it and preserve structure

**Comment by jpdakran** [comment]
@garry-t I am mainly curious of the structure around the failing secret. I do not need a full mocked file.

**Comment by garry-t** [comment]
@jpdakran 
```
docker-ruby-config: &docker-ruby-config
    image: cimg/ruby:2.5.8
    environment:
      AWS_IVS_REGION: eu-west-1
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      RAILS_ENV: test
      DEVISE_SECRET_KEY: REAL_SECRET_HERE
      DEVISE_JWT_SECRET_KEY: REAL_SECRET_HERE
      DEVISE_JWT_PRIVATE_KEY:  REAL_SECRET_HERE
      SECRET_KEY_BASE: REAL_SECRET_HERE
      LOCKBOX_MASTER_KEY: REAL_SECRET_HERE
      HOST: test.host
      PROTOCOL: http
      CDN_HOST: 'localhost:3000'
      CDN_PROTOCOL: 'http'
      E_API_SECRET:  STRING
      ACTIVE_CAMPAIGN_API_KEY:  API_TOKEN
      ACTIVE_CAMPAIGN_ENDPOINT: HTTPS
      MAIL_HOST: smtp
      LW_DIRECTKIT: https
      LW_BACKOFFICE: https:
      LW_WEBKIT: https:
      LW_LOGIN: login
      LW_PASS: pass
      LW_PDV: string
      API_PROTOCOL: http
      API_HOST: api.test.host
      SLACK_PAYMENT_TOKEN: 'https://hooks.slack.com/services/REAL_ID/REAL_ID/NUMBERS’
      M_PAY_CLIENT_ID: string
      M_PAY_API_KEY: API_KEY
      M_PAY_PREPRODUCTION: 'true'
      M_PAY_SYSTEM_USER: string
      M_PAY_USD_CREDIT_WALLET: 'CREDIT_USD'
      M_PAY_EUR_CREDIT_WALLET: 'CREDIT_EUR'
      M_PAY_EUR_SYSTEM_WALLET: SOME_ID
      M_PAY_EUR_FEE_WALLET: SOME_ID
      M_PAY_USD_SYSTEM_WALLET: SOME_ID
      M_PAY_USD_FEE_WALLET: SOME_ID
      EE_CONNECT_ACCOUNT_ID: ACC_ID
      EE_CONNECT_SECRET: REAL_SECRET
      EE_CONECT_PUBLISHABLE: string
      PDF_PATH: system_path
```

141 string it is this one SLACK_PAYMENT_TOKEN: 'https://hooks.slack.com/services/REAL_ID/REAL_ID/NUMBERS’
