### ISSUE TITLE
Changed or added secrets in existing files not detected

### ISSUE THREAD

**Issue by csurfleet** [Yelp/detect-secrets#665]
* **I'm submitting a possible bug but probable user error**

* **What is the current behavior?**
I have generated a baseline file and specified some known passwords. When I change that password, or add another password elsewhere in the file, it is not picked up by either detect-secrets scan or detect-secrets-hook

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
I have a compose file with this section in it:
```
mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
```
When I run ``detect-secrets scan > .baseline`` I get the baseline file. I then audit it, see the password and say that yes, it should be commited.

I commit the baseline file then modify my compose file to
```
mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changedpassword
      SOME_OTHER_PASSWORD: newpassword
```
I then run ``detect-secrets scan --baseline .baseline > .newsecrets`` but the resulting file is empty. I can also run ``detect-secrets-hook --baseline .baseline`` and see no results there either.

* **What is the expected behavior?**
I would expect both the changed password token and the new password to have been flagged to me by the subsequent commands. Hopefully I'm just missing a parameter or something? This seems basic so it must be user error!

* **Please tell us about your environment:**
  - detect-secrets Version: 1.4.0
  - Python Version: 3.9
  - OS Version: Windows 10
