### ISSUE TITLE
Kubernetes Secrets not detected.

### ISSUE THREAD

**Issue by guettli** [Yelp/detect-secrets#703]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**

detect-secrets did not detect this secret:

```
apiVersion: v1
data:
  foo: |
    YWMzN2Iysd2h2s8HG463....
kind: Secret
metadata:
  name: foo
type: Opaque
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Add above yaml file, and run `detect-secrets`.

* **What is the expected behavior?**

I want above secret to get detected.

* **What is the motivation / use case for changing the behavior?**

I don't want Kubernetes Secrets in my git repo.,

* **Please tell us about your environment:**
  - detect-secrets Version: 1.4.0
  - Python Version: 3.10
  - OS Version: Linux
  - File type (if applicable): yaml

* **Other information**
