### ISSUE TITLE
False Negative - YAML Parser Stops Reading After First String Value

### ISSUE THREAD

**Issue by RobertRosca** [Yelp/detect-secrets#791]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**

Secrets are not detected in (docker compose) yaml files when a top-level entry for a string is present.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

This will not detect any secrets:

```yaml
version: "3.8"

services:
  foo:
    environment:
      - SECRET_KEY=k0l7eDvHl2PhniP0Z146aCOeiw86LGJh5hS2i4LJM
```

But changing the first line to `version: 3.8` will:

```yaml
version: 3.8

services:
  foo:
    environment:
      - SECRET_KEY=k0l7eDvHl2PhniP0Z146aCOeiw86LGJh5hS2i4LJM
```

```text
ERROR: Potential secrets about to be committed to git repo!

Secret Type: Secret Keyword
Location:    ./foo.yaml:6
```

* **What is the expected behavior?**

Secrets to be detected when a string entry is present before some nested structure. 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - detect-secrets Version: 1.4.0
  - Python Version: 3.11.7
  - OS Version: Arch
  - File type (if applicable): yaml

* **Other information**

Problem seems to be with the yaml parser, for the buggy case of `version: "3.8"` the `lines` variable in `detect_secrets.scan:269` is:

```python
['version: "3.8"']
```

So nothing was parsed after that value, which is why the secret isn't found. For the working case of `version: 3.8` it is:

```python
[
  'version: 3.8\n',
  '\n', 'services:\n',
  '  foo:\n',
  '    environment:\n',
  '      - SECRET_KEY=k0l7eDvHl2PhniP0Z146aCOeiw86LGJh5hS2i4LJM\n'
]
```
